name       : smplayer-theme
version    : 18.6.0
release    : 1
source     :
    - https://sourceforge.net/projects/smplayer/files/SMPlayer-themes/18.6.0/smplayer-themes-18.6.0.tar.bz2/download : 2d86f4497dbeb3d5602bee2e0b2ed6ebf44ea90424c0b643b2597b4df277a985
license    :
    - CC-BY-2.5
    - CC-BY-SA-2.5
    - CC-BY-SA-3.0
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : desktop.theme
summary    : Themes for SMPlayer
description: |
    Themes for SMPlayer
builddeps  :
    - pkgconfig(Qt5Quick)
build      : |
    %make PREFIX=%PREFIX%
install    : |
    %make_install PREFIX=%PREFIX%

    # Remove license
    find $installdir/usr/share/smplayer/ -type f -name "README.txt" -exec rm -f {} \;